### ISSUE TITLE
Not working on RSS 1.0

### ISSUE THREAD

**Issue by sunshineo** [bobby-brennan/rss-parser#2]
Trying to use it on craigslist for example https://seattle.craigslist.org/search/act?format=rss
Got error

events.js:142
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'channel' of undefined
    at /Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/rss-parser/index.js:26:29
    at Parser.<anonymous> (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/xml2js/lib/xml2js.js:483:18)
    at emitOne (events.js:78:13)
    at Parser.emit (events.js:170:7)
    at Object.onclosetag (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/gordon/workspace/NoLostDog/nld-crawler/node_modules/xml2js/lib/xml2js.js:502:31)

**Comment by sunshineo** [comment]
[Error: Status code 301]

**Comment by bobby-brennan** [comment]
Thanks for the report. I started passing back an error for 1.0.  Feel free to send a PR that implements it, I'm sure it'd only take a few minutes.

Also opened #3 for the 301 error

**Comment by bobby-brennan** [comment]
Implemented in v2.10.0

**Comment by keithcollins** [comment]
Hey thanks for the parser, works great. Just wanted to let you know, I just started getting this on some feeds after updating to 2.10.0:

`Cannot read property 'channel' of undefined`

Went back to 2.9 and it stopped happening.

**Comment by bobby-brennan** [comment]
Hi Keith,

Do you have an example feed that's causes this error? If so I'll fix and add a test case.

**Comment by bobby-brennan** [comment]
I managed to trigger this error for malformed feeds (e.g. if the URL returns HTML instead of an RSS feed), but not for a legit RSS feed. Formerly malformed feeds would have passed an error to the callback, but in 2.10.0 it tries to parse them as RSS 1 and ends up throwing.

I added a check in 2.10.1 that will detect malformed feeds and pass an error to the callback rather than throwing.
