### ISSUE TITLE
Error: Attribute without value

### ISSUE THREAD

**Issue by fedeoppi** [bobby-brennan/rss-parser#77]
I get this exeptions and I can't understand what's the problem

`Error: Attribute without value
Line: 52
Column: 15
Char: s
    at error (c:\projects\myproject\node_modules\xml2js\node_modules\sax\lib\sax.js:651:10)
    at strictFail (c:\projects\myproject\node_modules\xml2js\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (c:\projects\myproject\node_modules\xml2js\node_modules\sax\lib\sax.js:1340:13)
    at Parser.exports.Parser.Parser.parseString (c:\projects\myproject\node_modules\xml2js\lib\parser.js:322:31)
    at Parser.parseString (c:\projects\myproject\node_modules\xml2js\lib\parser.js:5:59)
    at Promise (c:\projects\myproject\node_modules\rss-parser\lib\parser.js:30:22)
    at Promise (<anonymous>)
    at Parser.parseString (c:\projects\myproject\node_modules\rss-parser\lib\parser.js:29:16)
    at IncomingMessage.res.on (c:\projects\myproject\node_modules\rss-parser\lib\parser.js:97:23)
    at emitNone (events.js:110:20)`

Hope someone can help.

**Comment by bobby-brennan** [comment]
Can you share the feed you're trying to process? It sounds like the XML is invalid.

**Comment by bobby-brennan** [comment]
Closing this - if you can provide the XML happy to help
